name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest     # 用最新 Windows 镜像
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2

      - name: Configure
        run: cmake -B build -G "MinGW Makefiles"

      - name: Build
        run: cmake --build build --config Release

      - name: Run unit tests
        run: build\test_raw.exe